### ISSUE TITLE
Very long messages don't generate reasonable output

### ISSUE THREAD

**Issue by clockworksoul** [getgort/gort#165]
Long outputs (such as the help message from `kubectl`) don't generated reasonable output.

* Slack: A `invalid_blocks` appears, followed by the text in plain (not monospace) format
* Discord: An `Invalid Form Body` error is output.

## To replicate

Install and enable this bundle:

```yaml
gort_bundle_version: 1
name: kubectl
version: 0.0.1
description: Kubectl
docker:
    image: clockworksoul/kubectl
    tag: latest
commands:
    kubectl:
        executable: [/usr/local/bin/kubectl]
        rules:
            - allow
```

Execute the following command in Slack or Discord: `!kubectl --help`
