### ISSUE TITLE
Bundle "executable" should accept a list for subcommands 

### ISSUE THREAD

**Issue by clockworksoul** [getgort/gort#45]
Currently, a bundle command only accepts a single executable argument, so if a command binary has any subcommands, they MUST be subcommands of the bundle command too. This makes building rules harder.

```
commands:
  gort:
    description: "Bringing the power of the command line to chat."
    executable: "/bin/gort"
    rules:
      - allow
      - with arg[0] == "bundle" must have gort:manage_commands
      - with arg[0] == "group" must have gort:manage_groups
      - with arg[0] == "role" must have gort:manage_roles
      - with arg[0] == "user" must have gort:manage_users
```

If commands allowed multiple words (as Docker's [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) supports), we could do something like the following (perhaps):

```
commands:
  bundle:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "bundle" ]
    rules:
      - must have gort:manage_commands

  user:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "bundle" ]
    rules:
      - must have gort:manage_users

  version:
    description: "Bringing the power of the command line to chat."
    executable: [ "/bin/gort", "version" ]
    rules:
      - allow
```
