### ISSUE TITLE
Alternative profiles don't work on the command line

### ISSUE THREAD

**Issue by clockworksoul** [getgort/gort#75]
I have two profiles: `localhost` and `matt`. The first is an admin user, the second isn't, as follows:

```yaml
defaults:
    profile: localhost
localhost:
    url: http://localhost:4000
    password: <nope>
    user: admin
    allow_insecure: true
matt:
    url: localhost:4000
    password: <nah>
    user: matthew.titmus
    allow_insecure: true
```

Doing: `gort user list` on the command line as `admin` works, and the controller log provides this output:

```
INFO   [0956] REST service event                request="GET /v2/users HTTP/1.1" size=159 status=200 user=admin
```

Switching profiles:

```
$ go run . profile default matt
Profile 'matt' set to default.

$ go run . profile list        
Name         User              URL                      Default
localhost    admin             http://localhost:4000    
matt         matthew.titmus    http://localhost:4000       *
```

`matt` is now the default, however:

```
go $ run . user list
USERNAME  FULL NAME           EMAIL ADDRESS
admin     Gort Administrator  admin@gort
matthew.titmusmatt                matthew.titmus@gmail.com
```

(Note: formatting here is also broken)

Controller log still thinks it's `admin`

```
INFO   [1073] REST service event                request="GET /v2/users HTTP/1.1" size=159 status=200 user=admin
```

Same deal with using the `-P` flag:

```
go run . -P matt user list   
USERNAME  FULL NAME           EMAIL ADDRESS
admin     Gort Administrator  admin@gort
matthew.titmusmatt                matthew.titmus@gmail.com
```

Controller:

```
INFO   [1153] REST service event                request="GET /v2/users HTTP/1.1" size=159 status=200 user=admin
```

EDIT: Interestingly, if I stop and restart the server, the set default (`matt`) takes effect, but I can't change it back!

```
INFO   [0076] REST service event                 request="GET /v2/bundles HTTP/1.1" size=13 status=401 user=matthew.titmus
```

SECOND EDIT: Re-setting the default doesn't work. Perhaps it's just taking the last profile in the file?
